### YamlMime:PythonClass
uid: azure.mgmt.databox.v2021_03_01.models.CloudError
name: CloudError
fullName: azure.mgmt.databox.v2021_03_01.models.CloudError
module: azure.mgmt.databox.v2021_03_01.models
inheritances:
- azure.mgmt.databox._serialization.Model
summary: 'Cloud error.


  Variables are only populated by the server, and will be ignored when sending a request.'
constructor:
  syntax: 'CloudError(*, code: str | None = None, message: str | None = None, target:
    str | None = None, **kwargs: Any)'
variables:
- description: Cloud error code.
  name: code
  types:
  - <xref:azure.mgmt.databox.v2021_03_01.models.str>
- description: Cloud error message.
  name: message
  types:
  - <xref:azure.mgmt.databox.v2021_03_01.models.str>
- description: Cloud error target.
  name: target
  types:
  - <xref:azure.mgmt.databox.v2021_03_01.models.str>
- description: Cloud error details.
  name: details
  types:
  - <xref:azure.mgmt.databox.v2021_03_01.models.list>[<xref:azure.mgmt.databox.v2021_03_01.models.CloudError>]
- description: Cloud error additional info.
  name: additional_info
  types:
  - <xref:azure.mgmt.databox.v2021_03_01.models.list>[<xref:azure.mgmt.databox.v2021_03_01.models.AdditionalErrorInfo>]
