Exception: "<pending_xref py:class=\"CreateTasksErrorException\" py:module=\"azure.batch.custom.custom_errors\"\
  \ refdoc=\"azure.batch.custom\" refdomain=\"py\" refexplicit=\"False\" reftarget=\"\
  Exception\" reftype=\"class\" refwarn=\"False\">\n    <literal classes=\"xref py\
  \ py-class\">\n        Exception\n"
object: "<pending_xref py:class=\"TaskOperations\" py:module=\"azure.batch.operations\"\
  \ refdoc=\"azure.batch.operations\" refdomain=\"py\" refexplicit=\"False\" reftarget=\"\
  object\" reftype=\"class\" refwarn=\"False\">\n    <literal classes=\"xref py py-class\"\
  >\n        object\n"
str: "<pending_xref py:class=\"VerificationType\" py:module=\"azure.batch.models\"\
  \ refdoc=\"azure.batch.models\" refdomain=\"py\" refexplicit=\"False\" reftarget=\"\
  str\" reftype=\"class\" refwarn=\"False\">\n    <literal classes=\"xref py py-class\"\
  >\n        str\n"
